import Tree from './Tree/Tree'

let result
const test = new Tree([1,3,4,5,6,6.1,6.25,6.4,6.5,6.6,7,10,13,14])
test.append(0)
test.append(-1)
test.append(3)
// test.print(test.root)
// console.log('find', test.find(0))
// console.log('insert 5')
// test.insert(5)
// // test.print(test.root)
// console.log('test:', test)
// console.log('insert 6.7')
// test.insert(6.7)
// // test.print(test.root)
// console.log('append 8')
// test.append(8)
// // test.print(test.root)
// console.log('append 7')
// test.append(7)
// // test.print(test.root)
// console.log('append 7.5')
// test.append(7.5)
// // test.print(test.root)
// console.log('append 8.1')
// test.append(8.1)
// // test.print(test.root)
// console.log('append 8.01')
// test.append(8.01)
// // test.print(test.root)
// console.log('append 8.11')
// test.append(8.11)
// // test.print(test.root)
// console.log('append 6.9')
// test.append(6.9)
// test.print(test.root)
// console.log('insert 8')
// test.insert(8)
// test.print(test.root)
// console.log('insert 8.1')
// test.insert(8.1)
// test.print(test.root)
// console.log('insert 7.5')
// test.insert(7.5)
test.print(test.root)
console.log('traverse io ^^^^', test.traverse(console.log))
console.log('---')
console.log('traverse preo ^^^', test.traverse(console.log, 'preorder'))
console.log('---')
console.log('traverse posto ^^^', test.traverse(console.log, 'postorder'))
// console.log('find 13:', test.find(13))
// console.log('find 10:', test.find(10))
// console.log('find 14:', test.find(14))
// console.log('find 8.1:', test.find(8.1))
// console.log('remove 13')
// test.remove(13)
// test.print(test.root)
// console.log('removeAll 8.1')
// test.remove(8.1, true)
// test.print(test.root)
// console.log('insert 7')
// test.insert(7)
// test.print(test.root)
// console.log('insert 5.1')
// test.insert(5.1)
// test.print(test.root)
// console.log('insert 8')
// test.insert(8)
// test.print(test.root)
// console.log('remove 3')
// test.remove(3)
// test.print(test.root)
// console.log('remove 9')
// test.remove(9)
// test.print(test.root)
// console.log('insert 9')
// test.insert(9)
// test.print(test.root)
// console.log('insert 2')
// test.insert(2)
// test.print(test.root)
// console.log('insert -2')
// test.insert(-2)
// test.print(test.root)
// console.log('remove 6')
// test.remove(6)
// test.print(test.root)
// console.log('insert 6')
// test.insert(6)
// test.print(test.root)
// console.log('remove 6 again')
// test.remove(6)
// test.print(test.root)
// // console.log('remove 9', result = test.remove(9))
// // test.remove(9)
// // test.print(test.root)
// console.log('insert 6')
// test.insert(6)
// test.print(test.root)
// console.log('insert 9')
// test.insert(9)
// test.print(test.root)
// console.log('append 11')
// test.append(11)
// test.print(test.root)
// console.log('append 12')
// test.append(12)
// test.print(test.root)
// console.log('insert 12')
// test.insert(12)
// test.print(test.root)
// console.log('insert 11')
// test.insert(11)
// test.print(test.root)
