import Tree from './Tree'

let result
const test = new Tree([1,3,4,5,6,6.25,6.5,6.6,7,10,13,14])
test.append(0)
test.append(-1)
test.append(3)
test.prettyPrint(test.root)
console.log('find', test.find(0))
console.log('insert 5')
test.insert(5)
test.prettyPrint(test.root)
console.log('insert 6.7')
test.insert(6.7)
test.prettyPrint(test.root)
console.log('insert 8')
test.insert(8)
test.prettyPrint(test.root)
console.log('insert 7')
test.insert(7)
test.prettyPrint(test.root)
console.log('insert 5.1')
test.insert(5.1)
test.prettyPrint(test.root)
console.log('insert 8')
test.insert(8)
test.prettyPrint(test.root)
console.log('remove 3')
test.remove(3)
test.prettyPrint(test.root)
console.log('remove 9')
test.remove(9)
test.prettyPrint(test.root)
console.log('insert 9')
test.insert(9)
test.prettyPrint(test.root)
console.log('insert 2')
test.insert(2)
test.prettyPrint(test.root)
console.log('insert -2')
test.insert(-2)
test.prettyPrint(test.root)
console.log('remove 6')
test.remove(6)
test.prettyPrint(test.root)
console.log('insert 6')
test.insert(6)
test.prettyPrint(test.root)
console.log('remove 6 again')
test.remove(6)
test.prettyPrint(test.root)
console.log('remove 9', result = test.remove(9))
test.remove(9)
test.prettyPrint(test.root)
console.log('insert 6')
test.insert(6)
test.prettyPrint(test.root)
console.log('insert 9')
test.insert(9)
test.prettyPrint(test.root)
console.log('append 11')
test.append(10)
test.prettyPrint(test.root)
console.log('insert 11')
test.insert(10)
test.prettyPrint(test.root)
